title: Benson Truong
description: This website showcases my coding projects using R!
What does adding a return do | haai
Email: bensontruong@ucsb.edu
Phone: 626 221 2854
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman